language: go
sudo: false
matrix:
  include:
  - go: 1.x
    env: LATEST=true
  - go: tip
  allow_failures:
  - go: tip
before_install:
- go get github.com/mitchellh/gox
install:
- 
script:
- go get -t -v ./...
- if [ "${LATEST}" = "true" ]; then gox -os="linux darwin windows" -arch="amd64" -verbose
  ./...; fi
deploy:
  provider: releases
  file:
  - jproperties-translate_windows_amd64.exe
  - jproperties-translate_linux_amd64
  - jproperties-translate_darwin_amd64
  skip_cleanup: true
  on:
    repo: artificerpi/jproperties-translate
    tags: true
    condition: "$LATEST = true"
  api-key:
    secure: s5II0AnKrJXpaNgggglAdpSlp9hJYB3Vy/U9Ygb27VXT4IFcbBqLNFg0j0DO8fpBWcnknRhUCCnXzaVuYCSnDTJ6j4bvw8rZ4cSLWaj48/unkskKY1pVinCgvcJ0m/vhJgDYRGfFKOZFJCp6SROvd76korJLwofEQ8rrfv3/CsniQzrl3SinnFVwvHl9Yz7yVeAZHehNlLJHzrb9iOEh2VxJ4PUHuKrwHBUMO8Vo24q7dFrkGOJOCifPnvYa41gV3qfL5ZbF015TJXb9w5eJiwRa7VWzLnxf4evDaQ+CDOiH7Q7udzBys2bdZLRBfn6ON0eLV2eXtVa9M0Peg//Pk+g9AXqyzCevjX5rQJCfH2cWVCETTVWVX5P12Mopm8wbEJAwCw3qO3LDMfXasuxfv3kAvthJSRgUDCR9LBYfmCL9svS0t4wektJWmNK1DOQrRpoOFt5R4hubJCgrvpKPdPFH0X/+tvdipb7Qw9QxMLFMCXvXDqjkYQNUlBQ/cC/hCgJqKKvVQrqzhrZ8jymcDBByDsBacEVQtJyEyiHTO4GwqwyvCpfSCdqeqHVAbAD8bOZm4YhdDPiv+DLHGrUWBB4mfffljUYC/SX1mIihvIzGNcyO8qX4WQUD08eRy9lPaKSRjt4zd9e4lLO8HO5Zpe3TRvMFQ3reNJrxHmhGAPg=
